version: "3.8"
services:
  django:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - config/.env
    ports:
      - "8003:8000"
    networks:
      - aws_network
  
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql_mode="traditional" --max_allowed_packet=134217728
    restart: always
    ports:
      - "3368:3306"
    env_file:
      - config/.env
    networks:
      - aws_network
  
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    env_file:
      - config/.env

networks:
  aws_network: